### ISSUE TITLE
[Feature Request] Edit the Reminder after creation

### ISSUE THREAD

**Issue by pabloscloud** [thatsmanmeet/Tasky#10]
Its not possible to change the time after an reminder has been created

**Comment by thatsmanmeet** [comment]
Yeah currently it is not possible to change the date and time once the task has been created. In future releases this will be fixed and you would be able to change both time and date of a task. Thanks for suggestions.

**Comment by thatsmanmeet** [comment]
Hi @pabloscloud New version is out (v1.7), Now you can edit already created tasks.

**Comment by pabloscloud** [comment]
Yay
