### ISSUE TITLE
No date option

### ISSUE THREAD

**Issue by serrq** [thatsmanmeet/Tasky#100]
Set as default.

![1000115891](https://github.com/user-attachments/assets/dd377564-c3b9-4379-9673-604fd5e2f6eb)

**Comment by thatsmanmeet** [comment]
Hi @serrq, can you explain in little more detail what the issue is?

With new update the tasks will show default date when creating new task.

**Comment by thatsmanmeet** [comment]
Before this release, tasks were still added to the current day as default. The new update just shows the current date as default.

Even if I gave a toggle to disable showing the date, it will still have same effect.

**Comment by thatsmanmeet** [comment]
Ah I get it now. So you want some tasks to not have any date at all. Right? 

Hmm, I'll see what I can do here as this would require a fundamental change to app's code.
