### ISSUE TITLE
Recycle bin doesn't work properly

### ISSUE THREAD

**Issue by serrq** [thatsmanmeet/Tasky#102]
Android 14
Task 3.0.0
OnePlus CPH2399

If one pushes "delete" button within the "edit task" card, the task doesn't go in the recycle bin. Just disappear irreversibly.

![1000115894](https://github.com/user-attachments/assets/61515388-594c-4475-a301-0050ff0e9c05)

![1000115896](https://github.com/user-attachments/assets/1ba1059e-a44a-4bae-9ab4-f83f6b283a2c)

**Comment by thatsmanmeet** [comment]
I see. When pressing delete from edit task card it doesn't go to recycle bin but swiping a card to delete moves it to recycle bin.

Can you confirm that swiping puts the task in recycle bin but delete button from edit task doesn't?

**Comment by thatsmanmeet** [comment]
Noted. Will fix it in next release.

**Comment by thatsmanmeet** [comment]
Fixed
