### ISSUE TITLE
date and time truncated 

### ISSUE THREAD

**Issue by paulle** [thatsmanmeet/Tasky#106]
![Screenshot_20240727-182906](https://github.com/user-attachments/assets/fb0cda25-6b60-4061-8a7e-ba4fc38938c3)

**Comment by thatsmanmeet** [comment]
Did you increase font size on your phone?

**Comment by paulle** [comment]
Yes, i need it for reading

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 27.07.24 19:32 um Manmeet Singh schrieb :

**Comment by thatsmanmeet** [comment]
It sounds like increasing the font size is causing some trouble with the layout. Give it a shot with a smaller font and see if that helps. Longer words in your language can also mess with things a bit. Let me know if that doesn't fix it and we can figure something else out.

**Comment by paulle** [comment]
Yes decreasing does it. TI looks as it should. But for me it isn't a good solution because te smaller font size is hard to read for me.

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 27.07.24 19:42 um Manmeet Singh schrieb :

**Comment by thatsmanmeet** [comment]
I have searched for some solutions, apparently there are some hacks for this problem but nothing too concrete. 

I might try to implement some workaround to see if I can make the app work irrespective of system font size and providing a toggle to enable/disable this but again this is just a workaround and it might take some time to implement!

**Comment by paulle** [comment]
Thank you

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 29.07.24 14:22 um Manmeet Singh schrieb :
