### ISSUE TITLE
[Feature request] use rfc-3339/iso-8601 date format yyyy-mm-dd

### ISSUE THREAD

**Issue by jm355** [thatsmanmeet/Tasky#109]
I found a site a while ago that goes over all the reasons it's better, like how it's consistently big-endian like time (hh:mm:ss), but I can't seem to find it. Imo it's just much less confusing of a format, dd/mm/yyyy and mm/dd/yyyy are super easy to confuse because both are used regularly, but when you see the date start with "yyyy-", you know that the month is up next followed by the day. It's consistent and well defined and easier for me to read and understand

**Comment by thatsmanmeet** [comment]
You want this in add & edit tasks dialog right?

**Comment by jm355** [comment]
Yep
