### ISSUE TITLE
[Feature Request] Recurring reminders

### ISSUE THREAD

**Issue by pabloscloud** [thatsmanmeet/Tasky#11]
I want to read a chapter of a book each day and would need to create a new task ever day

**Comment by thatsmanmeet** [comment]
So you want repeating notifications everyday at a specific time. Sure, will add that to my bucket list of upcoming features.

**Comment by pabloscloud** [comment]
I wanted recurring reminders not recurring notifications, but that works for me too if that's easier to implement. Either works.

Recurring reminder:
"Read a chapter of the book"
-would need a complete task every -day

Recurring notification
"Read the book"
-task will be kept uncompleted every day until its done-

**Comment by thatsmanmeet** [comment]
I think recurring notifications would be much easier to implement. I will start working on it soon.

**Comment by thatsmanmeet** [comment]
Hi @pabloscloud , In new version v2.3, repeating tasks have been introduced. However the feature took way too long than I expected and is still in beta mode. Hence, I would really appreciate if you could test it and provide feedback after few days, so I can fix bugs and improve it. Rest Enjoy this new feature.

**Comment by pabloscloud** [comment]
Sure, I'll use it

**Comment by thatsmanmeet** [comment]
> Sure, I'll use it

How's your experience with recurring reminders ? Does it work without any problem ?

**Comment by pabloscloud** [comment]
Yes, works fine for me! Thanks!! 💙

**Comment by thatsmanmeet** [comment]
Great thanks for your feedback, time to move it out of beta.
