### ISSUE TITLE
[Feature Request] Android tasks integration

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [thatsmanmeet/Tasky#12]
Could you please consider adding standard Android tasks support so we can use DAVX5 to sync tasks with our servers like nextcloud?

**Comment by thatsmanmeet** [comment]
Sure, I can consider that.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I can appreciate your decision, but like a contacts app that doesn't integrate with the Android contacts system, a task app that doesn't integrate with the tasks system isn't very useful in my opinion.

**Comment by thatsmanmeet** [comment]
Hi I really appreciate your concern for the task integration. However DAVx5 integration seems to break the app so many times and without proper documentation it is really hard to implement it correctly. Also I want to keep this app simple and completely offline. So I had to make a tough decision to not implement syncing. Thanks for understanding.

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Actually, your app can stay completely offline. Check out the Tasks.org app also on fdroid. It's DAVX5 that needs internet permissions and handles the syncing and accounts. I use DAVX5 with the calendar and contacts apps from Simple Mobile Tools and all their apps lack the network permission.

**Comment by thatsmanmeet** [comment]
Ok I will give this couple of tries again. Maybe I should lookup the syncing code of various open source apps.

**Comment by thatsmanmeet** [comment]
Ok I will give this couple of tries again in the future until then I'll close this issue.
