### ISSUE TITLE
Bug: date is overlays on tasks

### ISSUE THREAD

**Issue by HotarunIchijou** [thatsmanmeet/Tasky#15]
When it's too many tasks and you should scroll to watch this, you can see that the date is overlays on tasks
![](https://user-images.githubusercontent.com/113282550/230706290-e890d14b-1caa-476e-951d-e73573a63d14.png)

**Comment by thatsmanmeet** [comment]
Ah, I see the date has a transparent background  due to which it is overlaying the task. I will fix it in the next update. Thanks for reporting this bug.

**Comment by thatsmanmeet** [comment]
Fixed with new update.
