### ISSUE TITLE
CalDAV support

### ISSUE THREAD

**Issue by Tealk** [thatsmanmeet/Tasky#17]
Hi

would it be possible to get CalDAV support? So you could securely store your tasks in Nextcloud and other services.

**Comment by thatsmanmeet** [comment]
Hi, There is an another issue too about DAVX5 integration. Currently I am unable to find any official documentation of davx5 or caldav for implementation. I will look deeper into this topic and see if I can implement it or not. Fingers crossed 🤞.

**Comment by Tealk** [comment]
Maybe this can help: https://www.davx5.com/
