### ISSUE TITLE
[Bug] Notification for completed tasks

### ISSUE THREAD

**Issue by pabloscloud** [thatsmanmeet/Tasky#19]
I ran into an issue where a notification shows up for a completed task. This happened yesterday and today for the same task. The notification showed up when I started my phone but also while using it normally.

https://user-images.githubusercontent.com/93644977/232183262-612d0fd1-300c-479f-b48d-37821772e521.mp4

**Comment by thatsmanmeet** [comment]
Bug Noted ✅

**Comment by thatsmanmeet** [comment]
Fixed with new release v2.2
