### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by k-svn** [thatsmanmeet/Tasky#20]
Where are the tasks stored? Is it possible to export the list to sync it with syncthing, nextcloud and so on?

**Comment by thatsmanmeet** [comment]
Tasks are stored locally on your android device using room database. Currently it is not possible to export or sync tasks lists. However there are plans to bring this feature in future releases.

**Comment by thatsmanmeet** [comment]
Hi, now it is possible to export the tasks to a zip file and restore from it on other device.

**Comment by CavaleriOmar** [comment]
Would it be possible to manually choose in which folder to save the files then, and synchronise them p2p with syncthing?
