### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [thatsmanmeet/Tasky#22]
ref: https://gitlab.com/fdroid/fdroiddata/-/commit/d07c14423eeb76e82a85180f1c999ebfcb50133e

Diff log: [tasky1.log](https://github.com/thatsmanmeet/Tasky/files/11438953/tasky1.log)

**Comment by licaon-kter** [comment]
let's reopen

ref: https://monitor.f-droid.org/builds/log/com.thatsmanmeet.taskyapp/27#site-footer

```
--- Tasky_v3.0.0/AndroidManifest.xml    2024-07-23 09:42:33.379454394 +0000
+++ com.thatsmanmeet.taskyapp_27/AndroidManifest.xml    2024-07-23 09:41:54.167819019 +0000
@@ -7,6 +7,7 @@
     <uses-permission android:name="android.permission.USE_EXACT_ALARM"/>
     <permission android:name="com.thatsmanmeet.taskyapp.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" android:protectionLevel="signature"/>
     <uses-permission android:name="com.thatsmanmeet.taskyapp.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"/>
+    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
     <application android:allowBackup="true" android:appComponentFactory="androidx.core.app.CoreComponentFactory" android:dataExtractionRules="@xml/data_extraction_rules" android:extractNativeLibs="false" android:fullBackupContent="@xml/backup_rules" android:icon="@mipmap/ic_logo" android:label="@string/app_name" android:supportsRtl="true" android:theme="@style/Theme.App.Starting">
         <receiver android:enabled="true" android:name="com.thatsmanmeet.taskyapp.notification.Notification"/>
         <activity android:configChanges="keyboardHidden|orientation|screenLayout|screenSize|uiMode" android:exported="true" android:name="com.thatsmanmeet.taskyapp.MainActivity" android:theme="@style/Theme.App.Starting">
```

**Comment by thatsmanmeet** [comment]
`AndroidManifest.xml` differs and from above logs I presume it's about `ACCESS_NETWORK_STATE`. Well, I had a problem where some library added this permission and I use merged manifest and deleted that permission and then built and published the app on the github. Idk how is this causing an error

**Comment by licaon-kter** [comment]
One should always build from the tagged commit, eg. https://github.com/thatsmanmeet/Tasky/commit/645c938b661e0346b136935958e5f2b769d4b6a3

>  I use merged manifest and deleted that permission 

which commit is that?

**Comment by thatsmanmeet** [comment]
same commit you mentioned

**Comment by licaon-kter** [comment]
Mmmmkay, please clean gradle cache and whatever other caches, rebuild, put the APK here so we can retest

**Comment by thatsmanmeet** [comment]
Ok, this one is from same commit `645c93`, without permission removed:  [Permission Not Removed APK](https://drive.google.com/file/d/1sRxfDZjwDHCmosDFHjf_FAT8tPO7Q9l7/view)

With permission removed: [Permission Removed Apk](https://drive.google.com/file/d/1fPjks5pIcKYHPRfA3tdKRXBqVOKueVC1/view)

**Comment by licaon-kter** [comment]
I think we are lost in translation.

F-Droid builds the recipe https://gitlab.com/fdroid/fdroiddata/-/commit/2c7275f277ce203b2e6b2a4ca19984912659945c

there is no "With permission removed" or "without permission removed", there are not two recipes, BUT ONLY one

Do you mean we need to ADD something to the recipe in order to remove that permission and match your published APK? 

What do you do exactly?

**Comment by thatsmanmeet** [comment]
No I mean that when I committed to github I'm not sure that if I deleted the permission from library using merged manifest or not. So I built the apk one with permission intact in manifest and one where I removed it.

You don't need to do anything or add any recipe. Just run the test on both apks and see which one works. 

Do update me!

**Comment by thatsmanmeet** [comment]
Let me explain in a little detail. Here's an issue [https://github.com/thatsmanmeet/Tasky/issues/84](https://github.com/thatsmanmeet/Tasky/issues/84 ) in which someone mentioned that my app have network permission when I haven't added any such permission in my app.

So, I searched online and found that some library may introduce such permissions without the developer knowing. So, In this update that I have released after a long time, I tried to address this issue.

In the manifest file you mentioned, I saw that network permission again, so I think it's due to the permission I tried to remove,

So, I was a bit confused whether the apk was built (with that unnecessary library permission) removed or not. So that's why I have given two apks. One with permission removed and one with permission not removed.

I hope I'm able to clear some things up

**Comment by licaon-kter** [comment]
All your code should be in this repo

All your APKs should be build from this code from this repo

The diff log above is from an APK built by me today from 645c938b661e0346b136935958e5f2b769d4b6a3 and shows that it has that permission.

If you want to remove that permission please commit the code changes that remove it, and I'll rebuild from that commit.

**Comment by thatsmanmeet** [comment]
It's done. I have commited the code. Should I also update the release apk in my releases?

**Comment by licaon-kter** [comment]
Yes, please remove tag, retag to https://github.com/thatsmanmeet/Tasky/commit/9ae21666fdc11c99d43dddc61ebb57c446118037 

rebuild from https://github.com/thatsmanmeet/Tasky/commit/9ae21666fdc11c99d43dddc61ebb57c446118037 and put that APK in the Tag

**Comment by thatsmanmeet** [comment]
Done ✅

**Comment by thatsmanmeet** [comment]
@licaon-kter thanks a lot. Also since you're here, I would like to ask that how can I change description, screenshots etc of my app on f-droid as my app is getting some new features.

**Comment by thatsmanmeet** [comment]
> what are these here exactly,: https://github.com/thatsmanmeet/Tasky/tree/master/fastlane/metadata/android ? 😛

I have been away from developing apps since december. Just forgot they even exists lol. Tell me I don't need to create a pull request at gitlab right?
 
> while you're at it rename these files: https://github.com/thatsmanmeet/Tasky/tree/master/fastlane/metadata/android/fr-FR as the need to have the same name as the en-US ones (not the same content of course)

I'll see what I need to do here.

> note that the changes will appear when the next version that contains the commits is published

Sure, I understand that.

**Comment by licaon-kter** [comment]
Yup, that's the whole point, you control them, autoupdates brings the changes, less work for everyone.
