### ISSUE TITLE
Task Groups

### ISSUE THREAD

**Issue by KyuutePrincess** [thatsmanmeet/Tasky#23]
I think task groups at the top could be really helpful to categorize each task to its group (also helpful if you want to make something like a shopping list) like in this example
![30c2e687-851a-421c-b336-02d813121b83.png](https://github.com/thatsmanmeet/Tasky/assets/131701519/e99e7be1-d521-41e1-9657-e5103f976d77)

**Comment by thatsmanmeet** [comment]
Hi I really like this idea but I currently this is not on my list. However I would be happy to have a PR for this feature. Thanks for your time.
