### ISSUE TITLE
24 h clock

### ISSUE THREAD

**Issue by paulle** [thatsmanmeet/Tasky#24]
Please can you an option for switching from am/pm to 24 hour
format.
Thank you

**Comment by thatsmanmeet** [comment]
Can you elaborate a little more on what do you mean by am/pm to 24 hour ?

**Comment by paulle** [comment]
When one choose a reminder in tasky where is only the posibility to choose the the time in a 12 hour format and using pm or am.
In Europe (don't know elsewhere) it's common tu use the 24 hour format. That means for example not 5pm it's 17.
Midnight is 24 or 0.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 24. Mai 2023, 16:27, schrieb Manmeet Singh :

**Comment by paulle** [comment]
Yes it is. Thank you very much

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 24. Mai 2023, 17:03, schrieb Manmeet Singh :

**Comment by thatsmanmeet** [comment]
Got it. In future release, I will provide an option in the app settings to switch between 12 hour and 24 hour clock view so it is accessible for both type of users.

**Comment by thatsmanmeet** [comment]
Currently the app is English only. Soon I will make a string file available to accept translation from contributors.

**Comment by thatsmanmeet** [comment]
New update is out. It have a toggle to switch between 24 hour and 12 hour clock format. Enjoy :)
