### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by paulle** [thatsmanmeet/Tasky#25]
There can I help to translate Tasky?
Is there string file?

**Comment by thatsmanmeet** [comment]
Sure your help will be appreciated. I will extract all the text from the app and will put it into a centralised string file. I will share the string file once I have extracted all the text in it. Thanks once again.

**Comment by paulle** [comment]
and here is the translation (german)
/home/krischan/Dokumente/resources string de german.txt

**Comment by thatsmanmeet** [comment]
Thank you for providing german translations. It will be implemented from next release.

**Comment by paulle** [comment]
S1 : Sicherung/Wiederherstellung

S2 : Sicherung oder Wiederherstellung ihrer Aufgaben durch eine lokale Zip-Datei

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 29. Mai 2023, 09:12, schrieb Manmeet Singh :
