### ISSUE TITLE
add posibility for an alarm sound

### ISSUE THREAD

**Issue by paulle** [thatsmanmeet/Tasky#30]
Please can you add posibility for an alarm sound?
I mean an alarm sound when a certain task is due at certain time.

thank you for the nice app

**Comment by thatsmanmeet** [comment]
You mean instead of normal default notification sounds, you can select your own custom sounds or ringtones from your device's local memory ?

**Comment by thatsmanmeet** [comment]
So If I understood you correctly, you want a notification sound that's only unique for my app ? 

PS: Don't feel bad for asking silly questions :)

**Comment by paulle** [comment]
Yes that's right

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 14. Juni 2023, 05:18, schrieb Manmeet Singh :

**Comment by thatsmanmeet** [comment]
The new version is out and has its own notification sound.

**Comment by paulle** [comment]
Thak you

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 30. Juni 2023, 15:06, schrieb Manmeet Singh :

**Comment by paulle** [comment]
Hi, changed some words in te values-de string and corrected a typo in my former translation.
See the string in the attachment.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 30. Juni 2023, 15:06, schrieb Manmeet Singh < ***@***.***>:
Closed #30 as completed.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/thatsmanmeet/Tasky/issues/30#event-9687694890">https://github.com/thatsmanmeet/Tasky/issues/30#event-9687694890", "url": "[https://github.com](<a href=)/thatsmanmeet/Tasky/issues/30#event-9687694890">https://github.com/thatsmanmeet/Tasky/issues/30#event-9687694890", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 33 lines (33 sloc) 2.91 KB
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Tasky</string>
    <string name="add_task_button">Aufgabe hinzufügen</string>
    <string name="add_task_dialog_title">Aufgabe hinzufügen</string>
    <string name="add_edit_text_placeholder">Was geht Ihnen im Kopf rum?</string>
    <string name="add_edit_dialog_select_date_button">Datum auswählen</string>
    <string name="add_edit_dialog_select_time_button">Zeitpunkt auswählen</string>
    <string name="add_edit_dialog_repeat_everyday">Täglich wiederholen</string>
    <string name="add_edit_dialog_set_reminder_title">Erinnerung festlegen (optional)</string>
    <string name="add_edit_dialog_add_button_text">Hinzufügen</string>
    <string name="add_edit_dialog_cancel_button_text">Abbrechen</string>
    <string name="edit_task_dialog_title">Aufgabe editieren</string>
    <string name="add_edit_dialog_edit_reminder_title">Erinnerung editieren</string>
    <string name="add_edit_dialog_save_button_text">Speichern</string>
    <string name="add_edit_dialog_delete_button_text">Löschen</string>
    <string name="task_complete_notification_message">Haben Sie Ihre Aufgabe heute erledigt ?</string>
    <string name="empty_list_no_tasks_text">Keine Aufgaben</string>
    <string name="permission_screen_title">Erlaubnis erforderlich</string>
    <string name="permission_screen_information_text">Beginnend mit Android 13+, Anwendungen benötigen Benachrichtigungserlaubnis um Benachrichtigungen anzuzeigen.</string>
    <string name="permission_screen_request_permission_button">Erlaubnis erforderlich</string>
    <string name="settings_screen_appbar_title">Einstellungen</string>
    <string name="separate_tasks_using_dates_title">Aufgaben trennen durch Verwendung von Daten</string>
    <string name="use_task_complete_animations_title">Verwendung von Animation bei erfüllter Aufgabe</string>
    <string name="enable_autostart_title">AutoStart aktivieren</string>
    <string name="enable_autostart_information_text">Bei einigen Geräten kommen die Benachrichtigungen nicht rechtzeitig oder funktionieren nicht nach einer Rebootbenachrichtigung. Klicken Sie hier um autostart zu aktivieren. \n\n(Nützlich für Xiaomi, vivo, Oppo ähnliche Geräte die stock rom verwenden)</string>
    <string name="view_source_title">Quelle ansehen</string>
    <string name="view_source_information_text">Tasky ist komplett quelloffen. Für Rückmeldungen oder Beteiligung an der Entwicklung ? besuchen Sie Github! Oh vergessen Sie nicht mir einen ⭐️ zu geben ;)</string>
    <string name="use_24_hour_clock">24-Stunden-Uhr verwenden</string>
    <string name="settings_backup_restore">Sicherung/Wiederherstellung</string>
    <string name="settings_backup_restore_information_text">Sicherung oder zu Wiederherstellung ihrer Aufgaben durch eine lokale Zip-Datei</string>
    <string name="use_task_complete_sounds_title">Verwende Töne bei erfüllter Aufgabe</string>
</resources>
Footer
© 2023 GitHub, Inc.
Footer navigation

**Comment by thatsmanmeet** [comment]
is this string file in the attachment updated ?

**Comment by paulle** [comment]
Yes the string file in the attachment is the updated string file.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 1. Juli 2023, 08:59, schrieb Manmeet Singh :
