### ISSUE TITLE
Black mode

### ISSUE THREAD

**Issue by tdpo2** [thatsmanmeet/Tasky#36]
Can you add Black mode?

**Comment by thatsmanmeet** [comment]
What do you mean by black mode ? If you are talking about theme then app can automatically switch between light and dark theme depending on your device theme. Are you referring to add dark theme / light theme toggle in the app settings ?

**Comment by tdpo2** [comment]
Yes. I mean't dark mode.

**Comment by tdpo2** [comment]
Also option for disabling sound for deleting task.

**Comment by thatsmanmeet** [comment]
> Yes. I mean't dark mode.

I will look into this.

> Also option for disabling sound for deleting task.

From next update the toggle for disabling animation sound will also disable the deletion sound too.

**Comment by thatsmanmeet** [comment]
Both issues fixed in new update.
