### ISSUE TITLE
[Feature Request] Change notification dialog

### ISSUE THREAD

**Issue by GilesMunn** [thatsmanmeet/Tasky#39]
Letting us add a task description would allow that to be used in the notification rather than "Have you completed your task?". Additionally, allowing us to set no text content on the reminder would be nice if you have multiple reminders at once. Thanks.

**Comment by thatsmanmeet** [comment]
Hi, that's a good idea. I will work through it.

**Comment by thatsmanmeet** [comment]
New update allows to add task description
