### ISSUE TITLE
Material You themed icon & pickers

### ISSUE THREAD

**Issue by verbumfeit** [thatsmanmeet/Tasky#4]
The app itself is styled, but the launcher icon and the date / time pickers are not.

(Otherwise great app, very clean)

**Comment by thatsmanmeet** [comment]
In the next, I will update the launcher icon to be themed, however google hasn't provided date or time pickers with material themeing as of now but it is planned. Once out will be implemented in the app.

**Comment by verbumfeit** [comment]
Oh google...
