### ISSUE TITLE
[Bug] Disabling "Use 24 Hour Clock" does nothing.

### ISSUE THREAD

**Issue by demonsako** [thatsmanmeet/Tasky#42]
Disabling "Use 24 Hour Clock" does nothing. It still shows up in the "Add Task" menus.

**Comment by thatsmanmeet** [comment]
Both 24 hour clock and non 24 hour clock have almost the same design. However you can see on the 24 hours clock there's no AM/PM on the sides and also more numbers appear inside the clock. It's a very small difference.

Please try using the toggle multiple times and see if it's working or not. I'll look into this.

**Comment by thatsmanmeet** [comment]
@paulle Is the 24 hour clock working ? It seems to work fine for me.

**Comment by paulle** [comment]
Yes the 24 hour clock is working for me.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 9. Juli 2023, 08:48, schrieb Manmeet Singh :

**Comment by thatsmanmeet** [comment]
> Yes the 24 hour clock is working for me.

Thanks a lot for confirmation. @demonsako check once again. Feature seems to work fine for us.

**Comment by demonsako** [comment]
Everything technically functions the way it's supposed to it's just a visual mistake in the edit menu. It works.

**Comment by thatsmanmeet** [comment]
Well I wouldn't call it a mistake just that it's default android clock used as time picker which can have a little visual change based on the toggle in settings. It's just a choice of visual preference. Rest assured everything will work the same irrespective of the toggle. For now I'm closing this issue.
