### ISSUE TITLE
[Feature Request] Change Notification Text

### ISSUE THREAD

**Issue by demonsako** [thatsmanmeet/Tasky#43]
It would be cool to change "Have you completed your ask today ?" to customized text. Great app otherwise.

**Comment by thatsmanmeet** [comment]
Sure I'll implement this feature in future updates.

**Comment by demonsako** [comment]
> Sure I'll implement this feature in future updates.
Awesome, thank you.

**Comment by thatsmanmeet** [comment]
New update allow to add description to task.
