### ISSUE TITLE
Option to mute in-app sounds

### ISSUE THREAD

**Issue by Innominatapersona** [thatsmanmeet/Tasky#46]
As there's a way to remove animation, I'd like to also toggle sounds.
I realized that when deleting a task, an awful sound comes out from speakers.
Please let me remove it.

Thanks

**Comment by thatsmanmeet** [comment]
Hello, there is a toggle in the settings to disable all the sounds from the app. `Use task complete sounds` toggle can be turned off and it will disable all the sounds from the app. If it's not working then see if you might be using an old version of the app. Please check that too.

**Comment by thatsmanmeet** [comment]
I hope that you might have found the toggle and I will be closing this issue. You can reopen this in future if you want.
