### ISSUE TITLE
Strange backspace behavior in task creation dialog

### ISSUE THREAD

**Issue by sburris0** [thatsmanmeet/Tasky#53]
Reproduction steps:
1. Enter `my test text` in the task name but do not add the task yet
2. Delete the last word with backspace to get `my test` as expected
3. Delete one more character to get `mytes` and notice that a space character has disappeared

Also works with longer strings. There seems to be something about deleting the last letter of the second-to-last word that causes the proceeding space to disappear.

**Comment by thatsmanmeet** [comment]
Well that is weird and I'm unable to reproduce this bug following your steps. Maybe you can send a video if you can for more clarification.
