### ISSUE TITLE
notificacion sound to choose

### ISSUE THREAD

**Issue by paulle** [thatsmanmeet/Tasky#54]
Please add an option to choose
the notification sound.
Sometimes I need a really strong and nagging notification
sound.
Thank you in advance

**Comment by paulle** [comment]
An option to select a notification sound

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 18. Okt. 2023, 07:43, schrieb gityhubi :

**Comment by thatsmanmeet** [comment]
Sure 👍

**Comment by thatsmanmeet** [comment]
Hi @paulle and @gityhubi , currently choosing a notification sound from settings is not an optimum solution as I am short on time, However I can make a toggle in the settings that allow you to toggle the current notification sound and your's system default notification sound. Will that be okay ? You could also suggest some notification sound for the app if you have any!

**Comment by thatsmanmeet** [comment]
Usually many android devices have option to choose custom notification sounds from app settings (by going into system settings) > notifications > sounds. So I can revert the app to default system sound is a much better step in long run!

**Comment by paulle** [comment]
Yes for me it would be ok.
I attached some sounds, maybe you don't like them, because they are nagging 😉

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 25. Okt. 2023, 12:54, schrieb Manmeet Singh :

**Comment by thatsmanmeet** [comment]
@paulle Where are attached sounds, I cannot find them ?

**Comment by thatsmanmeet** [comment]
Maybe your'e right, github doesn't allow this. However you can attach them by opening github and dragging files here in comment box. I need one finalised sound because it is impossible to change notification sound with every update as android system doesn't allows it.

**Comment by paulle** [comment]
It doesn't work, can put images in GitHub, but no sound files (ogg).

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 25. Okt. 2023, 16:16, schrieb Manmeet Singh :

**Comment by paulle** [comment]
Gesendet von Proton Mail für Mobilgeräte

If you write me with a "normal" email, not via GitHub, i can send you attachments.

-------- Original-Nachricht --------
Am 25. Okt. 2023, 16:31, schrieb Krischan :

**Comment by paulle** [comment]
It doesn't work, can put images here, but no sound files (ogg).

**Comment by thatsmanmeet** [comment]
I can't see your mail. So Send me a mail <a href="mailto:meetsdocsend@proton.me">here</a>
