### ISSUE TITLE
Fastlane issue: en-US shortdesc much too long

### ISSUE THREAD

**Issue by IzzySoft** [thatsmanmeet/Tasky#56]
Just to let you know that your `short_description.txt` for `en-US` is much too long. Per specification, it is limited to 80 chars; everything beyond that will simply be cut off. So you might wish to correct that. Thanks in advance!

Oh, and while on it: you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany that lonely PlayStore one to link to `https://apt.izzysoft.de/packages/com.thatsmanmeet.taskyapp/` :wink:

**Comment by thatsmanmeet** [comment]
So I need to correct the `short_description.txt` here on github only or have to make a merge request at gitlab too ?

As for a badge I'll add it again to the readme later on.

**Comment by IzzySoft** [comment]
You only need to update it here, it gets pulled automatically with the next release then. And thanks in advance for adding the badge :smiley:

**Comment by thatsmanmeet** [comment]
Done!

**Comment by IzzySoft** [comment]
Almost: No HTML in shortdesc, this must be "plain text". Can you please remove the `<p></p>`?

**Comment by thatsmanmeet** [comment]
Done :)

**Comment by IzzySoft** [comment]
Thanks!
