### ISSUE TITLE
Reminder not working on my phone 

### ISSUE THREAD

**Issue by sggo15** [thatsmanmeet/Tasky#60]
Solved

**Comment by thatsmanmeet** [comment]
Well it's weird because the notifications seem to work on all versions of android above 8. However I will look into it. 👍

**Comment by thatsmanmeet** [comment]
New update has been released of the app. It might be available on the playstore by tommorow. However you can download it right now from github if you want to test it. Uninstall previous app and try the new version and tell me if the problem is solved or not.

**Comment by sggo15** [comment]
> New update has been released of the app. It might be available on the playstore by tommorow. However you can download it right now from github if you want to don't want to wait till tommorow. Uninstall previous app and try the new version and tell me if the problem is solved or not.

Not solved,

**Comment by thatsmanmeet** [comment]
Did you completely uninstalled the previous app and then reinstalled this apk ?

**Comment by sggo15** [comment]
I think problem is I'm my phone ¿

**Comment by sggo15** [comment]
> Did you completely uninstalled the previous app and then reinstalled this apk ? 

Yes

**Comment by thatsmanmeet** [comment]
That could be the case because notifications are working on all the devices I tested. I thought maybe notification channel is the problem so in new update I recreated the channel but that doesn't seem to solve it.

Last step would be you trying to install the android studio and download entire code from github and run it on your device and share logs while waiting for notification. 

That's the only thing I think can tell whats the problem.

**Comment by thatsmanmeet** [comment]
Try setting a reminder for 1 minute and keep the app open when the time is over see if anything appears on the screen or not. Keep the app open and test it.

Do it with or without android studio.

**Comment by sggo15** [comment]
**Version 2.0**

![Screenshot_20231026-100651.png](https://github.com/thatsmanmeet/Tasky/assets/105706266/b9f298ee-8ec1-4575-b598-bcf08c869be8)

Showing **reminder** in notification settings .
But in letest not showing.

**Comment by sggo15** [comment]
> Try setting a reminder for 1 minute and keep the app open when the time is over see if anything appears on the screen or not. Keep the app open and test it.
> 
> Do it with or without android studio. 

Not working

**Comment by thatsmanmeet** [comment]
Ah I think it's the problem with notification channel. It should be reminders not reminder. I think your android system is not deleting the old notification channel. I don't why it's not deleting the old channel. Did you run the code through android. I think clear data the app and uninstall it and try installing two three times until reminders show up in settings.

**Comment by sggo15** [comment]
> Ah I think it's the problem with notification channel. It should be reminders not reminder. I think your android system is not deleting the old notification channel. I don't why it's not deleting the old channel. Did you run the code through android studio.> **No , I have not Desktop** I think clear data the app and uninstall it and try installing two three times until reminders show up in settings.

**Comment by sggo15** [comment]
Ohh , Now working thanks 😅👍🏻

**Comment by thatsmanmeet** [comment]
That's Great. Thanks for using my app! 🙌
