### ISSUE TITLE
[Feature request] multiple lists

### ISSUE THREAD

**Issue by Blendbolt** [thatsmanmeet/Tasky#69]
Hello there!
I was thinking that it could be really useful to be able to add secondary tasklists and to manage their settings separately. Like having an "agenda" list using dates and a basic to-do list without dates for example 🙂

Thanks for your lovely app, you're doing a great job!

**Comment by stendarr** [comment]
I for one really like the simple interface and that it doesn't try to do everything. I see it as a replacement for pen&paper todo lists. I can see the appeal of multiple lists but I think your use case might be more suited for a different, more feature-rich app.

**Comment by Blendbolt** [comment]
Alright I get your point :)

By the way, since last update, it's mandatory to fill every field but I don't get the point of it. In my opinion, it makes it more complicated because I usually don't use the description field and now I can't save new items without adding random character into it...

**Comment by stendarr** [comment]
I agree! I've been using it almost exclusively without entering a description so far and not being able to leave it blank is a bit of a bummer.

**Comment by bloodyeyesblackblood** [comment]
> I had kept task name and description optional because I used it for testing, so even in production I never cared.
> 
> However in last update one of the contributor submitted the code to make it mandatory for both name and description fields.
> 
> Now I'm confused. I can revert this changes back in next update but someone might again demand for making it mandatory.
> 
> It's so hard to cater to everyone's needs 😂. Maybe I might make description optional and keep name mandatory to satisfy everyone!

thats what settings are for mostly~ people should be able to decide for themself :) but i get the idea why some would like this :/

description should be def. optional by default.

---

i also would like to have completed reappearing tasks hidden for the day (a dropdown with hidden completed tasks cpuld be shown) what do u think of it?

**Comment by Blendbolt** [comment]
> thats what settings are for mostly~ people should be able to decide for themself :) but i get the idea why some would like this :/
> 
> description should be def. optional by default.
> 
> i also would like to have completed reappearing tasks hidden for the day (a dropdown with hidden completed tasks could be shown) what do u think of it?
> 
> alao checkboxes also should be customizable~ like serring 'em to the right side, but i think i should open new issues for it if they arent aleady got requested.

IMO the dropdown for completed tasks would make the interface more complicated and I guess that thatsmanmeet would give you the same answer as I got like "keeping the interface as simple as possible is the whole point of this app".
Personnaly I like to have my completed tasks always visible, it gives me some satisfying feeling to see what I already achieved meanwhile I check what I still have to do.
By the way, the animation for completed tasks is a simple but great idea, I always get a tiny and healthy dose of dopamine when it happens and it keeps my motivation up! 👍
