### ISSUE TITLE
[Feature Request] Ability to disable swipe to delete

### ISSUE THREAD

**Issue by Scrashdown** [thatsmanmeet/Tasky#70]
On my phone it's very easy to accidentally delete a task while scrolling through tasks, if my swipe gesture is not vertical enough.

Therefore, it would be nice to have the option to disable swipe to delete in the app settings.

Alternatively, we could also have a way to undo the last action, which would be useful when one accidentally deletes a task.

**Comment by thatsmanmeet** [comment]
Well new update includes a dialog box to prevent a task from being accidentally deleted by swipe.

**Comment by stendarr** [comment]
I believe the best solution would be the way for example Telegram and many other apps handle it:

If you swipe to delete, you get a small popup notification at the bottom of the screen that says you just deleted something and if you want it restored, there's a big fat return arrow at the rightmost side of the notification, along with maybe a 5s timer after which the entry is deleted for good.

While the confirmation prompt is helpful to prevent accidental deletes, it really negates the whole point of the swipe to delete gesture.

Right now, to delete, you can tap an entry and press delete, which is faster than swiping and tapping to confirm. So we have tap+tap vs swipe+tap, so the efficiency improvement of the swipe-to-delete is not really there anymore and the old method is faster.

Alternatively, to still have the efficiency improvement of swipe-to-delete without the risk of accidental deletes, you could implement a "wastebasket" of deleted tasks with the ability to restore them, but I think that would be harder to implement than the former option.

Also let me use this opportunity to thank you for this minimalist app! I have found myself using a lot of different todo apps over the years and this is the first one that does everything I need and is not bloated by tons of distracting features. Rarely have I found myself this invested in an app's development, so thanks a lot!
