### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [thatsmanmeet/Tasky#81]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, XDC, DASH, FTM, XRP, ADA, XMR addresses available for donations (addresses have to be copyable).

No longer go around websites (outside the app). See the new way: everything happens within the app (even offline).

Here some examples from other developers.

Unstoppable Wallet https://github.com/horizontalsystems/unstoppable-wallet-android

TimePlanner https://github.com/v1tzor/TimePlanner

![1000092943](https://github.com/roozbehzarei/filester/assets/113377431/ad34a018-66ae-4443-9d0c-484d17323161)

**Comment by thatsmanmeet** [comment]
Do you support buymeacoffee or github sponsors ?
