### ISSUE TITLE
Show the "description" field in list overview

### ISSUE THREAD

**Issue by serrq** [thatsmanmeet/Tasky#82]
For example:

Pay the hairdresser
15$

Both fields showns in the list view.

**Comment by thatsmanmeet** [comment]
I think that will add unnecessary clutter in the UI as long descriptions can make the UI look a little ugly. However I can make a new setting that can allow description to be shown below the title. So people based on their requirements can turn them off or on. Is that okay ?

**Comment by thatsmanmeet** [comment]
Sure, I'll work on it 👍
