### ISSUE TITLE
[Feature Request] Automatically set reminder day to today

### ISSUE THREAD

**Issue by Lppsoeht** [thatsmanmeet/Tasky#88]
It would save lots of time to me if the day was automatically set to the first day possible(today)
Or, also, it should work without setting the date but just the time(so it repeats everyday. Maybe it is already so but it does not work to me

**Comment by jm355** [comment]
Or have an option for the default day. I set most of my reminders for the next day ("tomorrow")

**Comment by thatsmanmeet** [comment]
Will resolve this in next update. Probably will set default day to the current date!

**Comment by thatsmanmeet** [comment]
Fixed in the new update which is coming soon
