### ISSUE TITLE
[Feature request] Celebration animation when task is completed

### ISSUE THREAD

**Issue by zoroya1** [thatsmanmeet/Tasky#9]
When user completes a tasks when he ticks task checkbox, have ribbons and other animation to make it satisfying :), ofc you can make animation toggable 

Examples are telegram app when one answers right question and also in Birday as when there is someone's birthday on current day

**Comment by thatsmanmeet** [comment]
Sure, I would add some animations when someone completes a task. Thanks for suggestion 🎉

**Comment by thatsmanmeet** [comment]
Hi, please check the video below and give some suggestions on it. 

In this case when you complete a task on tasky app, then "task completed" text will show on screen with confetti (sound will be changed from this video). Do you think it's okay or should it be changed ? 

https://user-images.githubusercontent.com/120583077/230341503-401f5a16-0772-4ff3-9abe-41dbd74c9c2c.mp4

**Comment by thatsmanmeet** [comment]
Added celebration animations in the new release v2.2 Enjoy 🙂
