### ISSUE TITLE
[Bug] Light theme doesnt work

### ISSUE THREAD

**Issue by inson1** [thatsmanmeet/Tasky#92]
![Screenshot_2024-02-12-20-33-11-329_com.thatsmanmeet.taskyapp.jpg](https://github.com/thatsmanmeet/Tasky/assets/75314629/a38db4c9-91da-4579-8e42-f0a34db1f645)

![Screenshot_2024-02-12-20-48-53-592_com.thatsmanmeet.taskyapp.jpg](https://github.com/thatsmanmeet/Tasky/assets/75314629/0542e011-6a7b-4726-bc20-b49bd59ff86b)

![Screenshot_2024-02-12-20-48-49-255_com.thatsmanmeet.taskyapp.jpg](https://github.com/thatsmanmeet/Tasky/assets/75314629/2a6e4a11-fba7-45d5-8b09-98322385ba77)

![Screenshot_2024-02-12-20-48-38-660_com.thatsmanmeet.taskyapp.jpg](https://github.com/thatsmanmeet/Tasky/assets/75314629/162dc1bd-c641-44aa-a89b-0243a15b5614)

It could be because of force dark theme? 

Xiaomi redmi note 8 pro

**Comment by thatsmanmeet** [comment]
> It could be because of force dark theme?

I think so, xiaomi default MIUI rom until verison 12 used to force dark theme on the all apps that made many apps looks awful and even break their theming. I don't know if newer version does that too. In any case maybe try disabling force dark mode. [Here's a youtube shorts](https://www.youtube.com/watch?v=LTY1YHsxor4), maybe try it and tell me if this fixes the issue or not. 

I have been using this app on different devices and the light mode seems to work fine on many different vendors. In the screenshots the App Bar seems fine as the colors are forced there, but on text the colors aren't forced and are applied by the OS itself. So, I assume that the problem mostly stems from the OS itself. So for now atleast try to disable `force dark mode` and see the results.

**Comment by thatsmanmeet** [comment]
Closing this issue as of now
